# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yml" }

    - { resource: "parameters.yml" }
    - { resource: "security.yml" }

framework:
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        handler_id: ~

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: Sylius\Migrations
    table_name: sylius_migrations
    name: Sylius Migrations

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"

fos_rest:
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

sylius_theme:
    sources:
        filesystem: ~

liip_imagine:
    filter_sets:
        sylius_shop_product_original:
            filters:
                # use and setup the "watermark" filter
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/watermark.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 45], mode: outbound }
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/watermark.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 106], mode: outbound }
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/watermark.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
        sylius_shop_product_thumbnail:
            filters:
                thumbnail: { size: [260, 184], mode: outbound }
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/watermark.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 389], mode: outbound }
                watermark:
                    # path to the watermark file (prepended with "%kernel.root_dir%")
                    image: ../web/watermark.png
                    # size of the water mark relative to the input image
                    size: 1
                    # set the position of the watermark
                    position: center
