# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin_dashboard_redirect:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_admin_dashboard
        permanent: true

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api


sylius_shop_product_index:
    path: /taxons/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: "@SyliusShop/Product/index.html.twig"
            grid: sylius_shop_product
            paginate: 9
    requirements:
        slug: .+

